version: '3.8'

services:
  elasticsearch:
    build: 
      context: ./
      dockerfile: Dockerfile.elastic_search
    restart: unless-stopped
    volumes:
      - data01:/usr/share/elasticsearch/data
    image: elasticsearch:v1
    container_name: elasticsearch
    environment:
      - "node.name=es-node"
      - "discovery.type=single-node"
      - "cluster.name=elastic-search-docker-cluster"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=true"
      - "xpack.security.authc.api_key.enabled=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.host=0.0.0.0"
      - "network.bind_host=0.0.0.0"
      - "network.publish_host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - public_frontend
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3

volumes:
  data01:
    driver: local

networks:
  public_frontend:
    driver: bridge
    external: true